# Generated by Django 6.1.1 on 2026-09-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
