# Generated by Django 6.1.1 on 2026-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_post_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
